services:
    review:
        container_name: review-service
        build:
            context: .
            args:
                service: review
        ports:
            - "80:80"
        networks:
            - productsstore-network
        restart: unless-stopped

    product:
        container_name: product-service
        build:
            context: .
            args:
                service: product
        environment:
            spring_profiles_active: compose
        ports:
            - "8080:8080"
        networks:
            - productsstore-network
        restart: unless-stopped

networks:
    productsstore-network:
        driver: bridge
