server:
    port: 80
    error:
        include-message: always
        include-exception: true
spring:
    mvc:
        pathmatch:
            # For compatibility with SpringFox Swagger implementation
            matching-strategy: ant_path_matcher
    datasource:
        # mem -> the DB physical storage is the service process memory itself
        # The DB is volatile: it is reinitialized whenever the service is restarted
        # Good for demo purposes, not good at all for a real production of course
        # To switch to persistent DB on filesystem use jdbc:h2:file:<PATH_ON_FS>
        url: jdbc:h2:mem:productsdb
        username: admin
        password: password
        driverClassName: org.h2.Driver
    jpa:
        # Service does not use views so default open-in-view: true just lead to a redundant warning message at service startup
        open-in-view: false
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        # In order to run datasource initialization script src/main/resources/data.sql after the DB schema is generated by Hibernate
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
            settings:
                # Allow connection to h2 web console from external hosts.
                # Required to browse the web console on Docker daemon host when the servoce is runnning as a Docker container
                web-allow-others: true
