microservice:
    version: 1.0.0
server:
    port: 8080
    error:
        include-message: always
        include-exception: true
springdoc:
    swagger-ui:
        path: /
review-service:
    domain-name: "localhost"
