microservice:
    version: {{cookiecutter.version}}
server:
    port: {{cookiecutter.port}}
    error:
        include-message: always
        include-exception: true
springdoc:
    swagger-ui:
        path: /
